//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongVan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int DIENBIEN { get; set; }
        public int NGUOIBINHLUAN { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
    
        public virtual CANBO NguoiBinhLuan{ get; set; }
        public virtual DIENBIENCUOCHOP DienBienCuocHop { get; set; }
    }
}
