//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongVan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANBO
    {
        public CANBO()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.DIENBIENCUOCHOPs = new HashSet<DIENBIENCUOCHOP>();
            this.DIENBIENCUOCHOPs1 = new HashSet<DIENBIENCUOCHOP>();
            this.KEHOACHHOPs = new HashSet<KEHOACHHOP>();
            this.KEHOACHHOPs1 = new HashSet<KEHOACHHOP>();
            this.MOIHOPs = new HashSet<MOIHOP>();
            this.TAIKHOANDANGNHAPs = new HashSet<TAIKHOANDANGNHAP>();
        }
    
        public int ID { get; set; }
        public short GIOITINH { get; set; }
        public string USERNAME { get; set; }
        public string MANV { get; set; }
        public string HONHANVIEN { get; set; }
        public string TENNHANVIEN { get; set; }
        public string NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public Nullable<bool> COHIEULUC { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual GIOITINHCANBO GIOITINHCANBO { get; set; }
        public virtual TAIKHOANDANGNHAP TAIKHOANDANGNHAP { get; set; }
        public virtual ICollection<DIENBIENCUOCHOP> DIENBIENCUOCHOPs { get; set; }
        public virtual ICollection<DIENBIENCUOCHOP> DIENBIENCUOCHOPs1 { get; set; }
        public virtual ICollection<KEHOACHHOP> KEHOACHHOPs { get; set; }
        public virtual ICollection<KEHOACHHOP> KEHOACHHOPs1 { get; set; }
        public virtual ICollection<MOIHOP> MOIHOPs { get; set; }
        public virtual ICollection<TAIKHOANDANGNHAP> TAIKHOANDANGNHAPs { get; set; }
    }
}
