//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongVan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KEHOACHHOP
    {
        public KEHOACHHOP()
        {
            this.DIENBIENCUOCHOPs = new HashSet<DIENBIENCUOCHOP>();
            this.MOIHOPs = new HashSet<MOIHOP>();
        }
    
        public int ID { get; set; }
        public int CUOCHOP { get; set; }
        public int DIADIEM { get; set; }
        public int NGUOICHUTRI { get; set; }
        public int TRANGTHAI { get; set; }
        public Nullable<int> THUKY { get; set; }
        public Nullable<System.DateTime> NGAYGIOBATDAU { get; set; }
        public Nullable<int> SONGUOI { get; set; }
        public Nullable<System.DateTime> THOIGIANTIENHANH { get; set; }
        public Nullable<bool> COHIEULUC { get; set; }
    
        public virtual CANBO CANBO { get; set; }
        public virtual CANBO CANBO1 { get; set; }
        public virtual CUOCHOP CUOCHOP1 { get; set; }
        public virtual DIADIEM DIADIEM1 { get; set; }
        public virtual ICollection<DIENBIENCUOCHOP> DIENBIENCUOCHOPs { get; set; }
        public virtual TRANGTHAIKEHOACH TRANGTHAIKEHOACH { get; set; }
        public virtual ICollection<MOIHOP> MOIHOPs { get; set; }
    }
}
