//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongVan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOMCOQUYEN
    {
        public int NHOM { get; set; }
        public int QUYENTRUYCAP { get; set; }
        public Nullable<bool> KICHHOAT { get; set; }
    
        public virtual NHOMQUYEN NHOMQUYEN { get; set; }
        public virtual QUYENTRUYCAP QUYENTRUYCAP1 { get; set; }
    }
}
