//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongVan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanlyhopEntities : DbContext
    {
        public QuanlyhopEntities()
            : base("name=QuanlyhopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BINHLUAN> BINHLUANs { get; set; }
        public DbSet<CANBO> CANBOes { get; set; }
        public DbSet<COQUYEN> COQUYENs { get; set; }
        public DbSet<CUOCHOP> CUOCHOPs { get; set; }
        public DbSet<DIADIEM> DIADIEMs { get; set; }
        public DbSet<DIENBIENCUOCHOP> DIENBIENCUOCHOPs { get; set; }
        public DbSet<GIOITINHCANBO> GIOITINHCANBOes { get; set; }
        public DbSet<KEHOACHHOP> KEHOACHHOPs { get; set; }
        public DbSet<LOAIDIENBIEN> LOAIDIENBIENs { get; set; }
        public DbSet<MOIHOP> MOIHOPs { get; set; }
        public DbSet<NHOMCOQUYEN> NHOMCOQUYENs { get; set; }
        public DbSet<NHOMQUYEN> NHOMQUYENs { get; set; }
        public DbSet<QUYENTRUYCAP> QUYENTRUYCAPs { get; set; }
        public DbSet<QUYETDINHCUANGUOINHAN> QUYETDINHCUANGUOINHANs { get; set; }
        public DbSet<TAIKHOANDANGNHAP> TAIKHOANDANGNHAPs { get; set; }
        public DbSet<TRANGTHAIDANGNHAP> TRANGTHAIDANGNHAPs { get; set; }
        public DbSet<TRANGTHAIKEHOACH> TRANGTHAIKEHOACHes { get; set; }
    }
}
