//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongVan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYENTRUYCAP
    {
        public QUYENTRUYCAP()
        {
            this.COQUYENs = new HashSet<COQUYEN>();
            this.NHOMCOQUYENs = new HashSet<NHOMCOQUYEN>();
        }
    
        public int ID { get; set; }
        public string TENQUYEN { get; set; }
        public Nullable<long> VALUE { get; set; }
    
        public virtual ICollection<COQUYEN> COQUYENs { get; set; }
        public virtual ICollection<NHOMCOQUYEN> NHOMCOQUYENs { get; set; }
    }
}
