//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongVan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANDANGNHAP
    {
        public TAIKHOANDANGNHAP()
        {
            this.CANBOes = new HashSet<CANBO>();
            this.COQUYENs = new HashSet<COQUYEN>();
            this.NHOMQUYENs = new HashSet<NHOMQUYEN>();
        }
    
        public string USERNAME { get; set; }
        public int ID_CANBO { get; set; }
        public int TRANGTHAIDANGNHAP { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> DANGNHAPSAUCUNG { get; set; }
        public Nullable<bool> COHIEULUC { get; set; }
    
        public virtual ICollection<CANBO> CANBOes { get; set; }
        public virtual CANBO CANBO { get; set; }
        public virtual ICollection<COQUYEN> COQUYENs { get; set; }
        public virtual TRANGTHAIDANGNHAP TRANGTHAIDANGNHAP1 { get; set; }
        public virtual ICollection<NHOMQUYEN> NHOMQUYENs { get; set; }
    }
}
