//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUOCHOP
    {
        public CUOCHOP()
        {
            this.KEHOACHHOPs = new HashSet<KEHOACHHOP>();
        }
    
        public int ID { get; set; }
        public string TEN { get; set; }
        public string CHUDE { get; set; }
        public Nullable<bool> COHIEULUC { get; set; }
    
        public virtual ICollection<KEHOACHHOP> KEHOACHHOPs { get; set; }
    }
}
