//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIENBIENCUOCHOP
    {
        public DIENBIENCUOCHOP()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
        }
    
        public int ID { get; set; }
        public int ID_KEHOACH { get; set; }
        public int ID_LOAI { get; set; }
        public Nullable<int> TACGIA { get; set; }
        public int NGUOIGHI { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual CANBO CANBO { get; set; }
        public virtual CANBO CANBO1 { get; set; }
        public virtual KEHOACHHOP KEHOACHHOP { get; set; }
        public virtual LOAIDIENBIEN LOAIDIENBIEN { get; set; }
    }
}
