//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHAIDANGNHAP
    {
        public TRANGTHAIDANGNHAP()
        {
            this.TAIKHOANDANGNHAPs = new HashSet<TAIKHOANDANGNHAP>();
        }
    
        public int ID { get; set; }
        public string YNGHIA { get; set; }
    
        public virtual ICollection<TAIKHOANDANGNHAP> TAIKHOANDANGNHAPs { get; set; }
    }
}
